In [4]:
import multiprocessing
n_cpu = multiprocessing.cpu_count()
print(n_cpu)

12


In [11]:
import numpy as np

a = [[0, 1, 2], [3, 4, 5], [6, 7, 8]]
b = [[8, 7, 6], [5, 4, 3], [2, 1, 0]]
a = np.array(a)
b = np.array(b)
print(b*a)
print(np.ones((3,3))*1.1)

[[ 0  7 12]
 [15 16 15]
 [12  7  0]]
[[1.1 1.1 1.1]
 [1.1 1.1 1.1]
 [1.1 1.1 1.1]]


In [9]:
import numpy as np
import cv2

a = cv2.imread('raw_image.tif')
b = np.uint8(255)
print(type(a))
print(type(b))

<class 'numpy.ndarray'>
<class 'numpy.uint8'>


In [2]:
import numpy as np
i = range(10)
print(np.size(i))

10


In [ ]:
import numpy as np
i = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(i[-6:-1])

[]


In [61]:
import numpy as np
i = list(range(1,31))
print(i[10:20:-1])

[]


In [63]:
import numpy as np
i = nested_list = [[i * 9 + j + 1 for j in range(9)] for i in range(9)]
i = np.array(i)
j = [[1,2,3],[4,5,6],[7,8,9]]
j = np.array(j)
print(np.flip(j, axis=0))
print(i[::-1,::-1])

[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[81 80 79 78 77 76 75 74 73]
 [72 71 70 69 68 67 66 65 64]
 [63 62 61 60 59 58 57 56 55]
 [54 53 52 51 50 49 48 47 46]
 [45 44 43 42 41 40 39 38 37]
 [36 35 34 33 32 31 30 29 28]
 [27 26 25 24 23 22 21 20 19]
 [18 17 16 15 14 13 12 11 10]
 [ 9  8  7  6  5  4  3  2  1]]


In [14]:
import multiprocessing
n_cpu = multiprocessing.cpu_count()
print(n_cpu)

20


In [17]:
import numpy as np
print(np.arange(-16,16))

[-16 -15 -14 -13 -12 -11 -10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1
   2   3   4   5   6   7   8   9  10  11  12  13  14  15]


In [19]:
i = range(10)

for i in range(10):
    print(i) 

0
1
2
3
4
5
6
7
8
9
